PACKAGEROOT=/Users/mdecorte/Documents/Development/Lambda/thirdSource
include $(PACKAGEROOT)/config.make/make.header

# LOG_LEVEL=error
#############################################################
SRC= \
	src/index.js					\
	src/logger.js					\
	src/validator.js				\
	src/packageConfig.js			\
	src/guid.js						

UNITTESTSRC= \
	test/guid-unit.test.js	\
	test/packageConfig-module.unit.test.js	\
	test/packageConfig-moduleLoad.unit.test.js	\
	test/packageConfig-package.unit.test.js	\
	test/packageConfig-packageLoad.unit.test.js	

INTTESTSRC= 

TFSOURCE=

SUBPACKAGES=


############################################################

all: 

init: npm.init
init: package

npm.init:
	npm install

unit: 

package: 

environment: 

install: 

integration: 

test: 

clean: 

veryclean: 

############################################################
include $(PACKAGEROOT)/config.make/make.footer


