PACKAGEROOT=/Users/mdecorte/Documents/Development/Lambda/thirdSource
include $(PACKAGEROOT)/config.make/make.header

#############################################################

# LOG_LEVEL=trace

SRC= \
	src/authenticateTestUser.js


UNITTESTSRC= \
	test/authenticateTestUser.unit.test.js

INTTESTSRC= 

TFSOURCE=

SUBPACKAGES=

############################################################

all: 

init: npm 
init: package

npm:
	npm install --save-dev
	npm install --prefix .. promise 
	npm install --prefix .. joi

unit: 

package: 

environment: 

install: 

integration: 

test: 

clean: 

veryclean: 

############################################################
include $(PACKAGEROOT)/config.make/make.footer


