# PACKAGEROOT=/Users/mdecorte/Documents/Development/Lambda/thirdSource
include $(PACKAGEROOT)/config.make/make.header

#############################################################

# LOG_LEVEL=trace

SRC= \
	src/authenticateTestUser.js 			\
	src/testUser.js


UNITTESTSRC= \
	test/authenticateTestUser.unit.test.js	\
	test/testUser.unit.test.js

INTTESTSRC= 

TFSOURCE=

SUBPACKAGES=

############################################################

all: 

init: npm 
init: package


npm:
	npm install 

unit: 

package: 

environment: 

install: 

integration: 

test: 

clean: 

veryclean: 

############################################################
include $(PACKAGEROOT)/config.make/make.footer


