# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax
# AWS CodeBuild configuration file
    
version: 0.2
phases:
  install:
    commands:
      - cd HelloWorld2
      - npm install 
      - aws s3 cp main.js s3://mrd_codebucket
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket mrd_codebucket --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    