# AWS CodeBuild Build instructions
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
    
version: 0.2
phases:
  install:
    commands:
      - cd HelloWorld2
      - npm install
      - ls
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket mdecorte-codebucket --output-template-file NewSamTemplate.yaml
      - ls
artifacts:
  type: zip
  files:
    - */samTemplate.yaml
    