# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# AWS application deployment configuration file

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World2

Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 16
    MemorySize: 128

Resources:
  helloworld2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: s3://mdecorte-codebucket/code.zip
      # CodeUri: ./

    DeploymentPreference:
      Type: All-at-once
