# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md
# AWS application deployment configuration file

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      Runtime: nodejs6.10
      CodeUri: ./
