# AWS CodeBuild Build instructions
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
    
version: 0.2
phases:
  install:
    commands:
      - cd HelloWorld2
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ${s3bucket} --output-template-file newSamTemplate.yaml
      - ls -FR
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    