PACKAGEROOT=/Users/mdecorte/Documents/Development/Lambda/thirdSource
include $(PACKAGEROOT)/config.make/make.header

# LOG_LEVEL=error
#############################################################
SRC= \
	src/methodRouter.js

UNITTESTSRC= \
	test/methodRouter-unit.test.js

INTTESTSRC= 

TFSOURCE=

SUBPACKAGES=


############################################################

all: 

init: npm

npm:
	npm install
	npm install --prefix .. joi
	npm install --prefix .. promise

unit:

package:

environment: 

install: 

integration: 

test: 

clean: 

veryclean: 

############################################################
include $(PACKAGEROOT)/config.make/make.footer


