PACKAGEROOT=/Users/mdecorte/Documents/Development/Lambda/thirdSource
include $(PACKAGEROOT)/config.make/make.header

#############################################################

# LOG_LEVEL=trace

SRC= \
	src/environment.js


UNITTESTSRC= \
	test/environment.unit.test.js

INTTESTSRC= 

TFSOURCE=

SUBPACKAGES=


############################################################

all: 

init: npm 

npm:
	npm install

unit: 

package: 

environment: 

install: 

integration: 

test: 

clean: 

veryclean: 

############################################################
include $(PACKAGEROOT)/config.make/make.footer


